export enum BaaSCallbackOriginEnum {
  OPERATOR_CREATED = 'OPERATOR_CREATED',

  // blocked = true or false
  OPERATOR_BLOCKED = 'OPERATOR_BLOCKED',

  ACCOUNT_CREATE = 'ACCOUNT_CREATE',
  TRANSACTION_FEE = 'TRANSACTION_FEE',

  // clocked, unblocked, canceled
  ACCOUNT_STATUS_CHANGE = 'ACCOUNT_STATUS_CHANGE',

  // contracted, renewed,
  SERVICE_PLAN = 'SERVICE_PLAN',

  WITHDRAW_CARD = 'WITHDRAW_CARD',
  PURCHASE_CARD = 'PURCHASE_CARD',
  TED_CASHIN = 'TED_CASHIN',
  TED_CASHOUT = 'TED_CASHOUT',
  P2P = 'P2P',
  PAYMENT = 'PAYMENT',

  PAYMENT_SLIP = 'PAYMENT_SLIP',
  PIX_CREDIT = 'PIX_CREDIT',
  PIX_DEBIT = 'PIX_DEBIT',
  PIX_REVERSAL_DEBIT = 'PIX_REVERSAL_DEBIT',
  PIX_REVERSAL_CREDIT = 'PIX_REVERSAL_CREDIT',
}
