export type AccountIndividualResponse = {
  id: string,
  account_number: string,
  email: string,
  individual_id: string,
  company_id: string,
  full_name: string,
  document: string,
  account_type: string,
  status: string,
  status_description: string,
  canceled_date: string,
  blocked: boolean,
  username: string,
  balance: string,
  balance_cents: number,
  last_access: Date,
  avatar_url: string,
  alias_account: {
    account_digit: string,
    account_number: string,
    account_status: string,
    account_type: string,
    bank_number: string,
    branch_digit: string,
    branch_number: string,
    created_date: Date,
    new_account_number: string,
    old_account_number: string
  },
  external_blocked: boolean,
  created_at: Date,
  updated_at: Date
}